<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="image\Снимок.PNG" />
    <None Remove="imagleee\fgsdg.PNG" />
    <None Remove="ttt\fgsdg.PNG" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ttt\fgsdg.PNG" />
  </ItemGroup>

</Project>
